---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: prometheus
  namespace: flux-system
spec:
  interval: 24h
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  interval: 24h
  chart:
    spec:
      chart: kube-prometheus-stack
      version: '55.8.3'
      sourceRef:
        kind: HelmRepository
        name: prometheus
  values:
    alertmanager:
      alertmanagerSpec:
        nodeSelector:
          cncf-project: wg-green-reviews
          cncf-project-sub: internal

    grafana:
      ingress:
        enabled: true
      nodeSelector:
        cncf-project: wg-green-reviews
        cncf-project-sub: internal

    kube-state-metrics:
      nodeSelector:
        cncf-project: wg-green-reviews
        cncf-project-sub: internal

    prometheus:
      prometheusSpec:
        nodeSelector:
          cncf-project: wg-green-reviews
          cncf-project-sub: internal

        serviceMonitorSelectorNilUsesHelmValues: false

    prometheusOperator:
      admissionWebhooks:
        patch:
          nodeSelector:
            cncf-project: wg-green-reviews
            cncf-project-sub: internal

        deployment:
          nodeSelector:
            cncf-project: wg-green-reviews
            cncf-project-sub: internal

      nodeSelector:
        cncf-project: wg-green-reviews
        cncf-project-sub: internal

  targetNamespace: monitoring
